package com.deloitte.Auth_Service.mapper;

import com.deloitte.Auth_Service.dto.SignupRequestDto;
import com.deloitte.Auth_Service.dto.UserServiceRequestDto;

public class UserServiceMapper {

    public static UserServiceRequestDto toUserServiceRequestDto(SignupRequestDto signupRequest) {
        if (signupRequest == null) {
            return null;
        }

        return new UserServiceRequestDto(
                null, // id will be generated by User Service
                signupRequest.getName(),
                signupRequest.getEmail(),
                signupRequest.getContact(),
                signupRequest.getDateOfBirth() != null ? signupRequest.getDateOfBirth().toString() : null,
                signupRequest.getAddress() != null ? signupRequest.getAddress() : "",
                signupRequest.getPassword(),
                (signupRequest.getGender() != null && !signupRequest.getGender().isBlank())
                        ? signupRequest.getGender()
                        : "UNSPECIFIED" // Default gender if not provided
        );
    }
}

